### ISSUE TITLE
What if server responses are out-of-order?

### ISSUE THREAD

**Issue by pohlt** [nens/asyncio-rpc#3]
I might be totally wrong, but while browsing through your code, I got the impression that you seem to assume that server responses have the same ordering as the requests (and throw away out-of-order responses). Am I right?

Could be an issue for RPC services which cannot guarantee such an in-order processing.

I'm currently working on a similar topic and found this repo. Thanks for your work!

**Comment by jpprins1** [comment]
Extremely late reaction: but good point, the ordering is currently fixed.
